name: Update Readme
on:
    push:
        branches:
            - main
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * 0"
jobs:
    run-script-and-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 23
                  cache: "npm"

            - run: npm ci
            - run: AUTH_TOKEN={{ github token here please }} npm run start

            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
              commit_message: "chore: update readme"
